[package]
name = "otto-billing"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
otto-tenant.workspace = true
otto-core.workspace = true
sqlx.workspace = true
serde.workspace = true
chrono.workspace = true
schemars.workspace = true
